-- =====================================================================
-- 7527iptal.org - Gonullu kayitlari
-- Supabase Dashboard > SQL Editor'de BIR KEZ calistirin.
--
-- KISISEL VERI UYARISI:
--   Bu tablo ad, iletisim (telefon/e-posta) ve sehir tutar -> KVKK kapsamindadir.
--   Tablo anon/authenticated'a KAPALIDIR; disariya yalnizca toplam sayi acilir.
--   Kayitlari yalnizca Supabase panelinden yetkili kisiler gorebilir.
-- =====================================================================

create table if not exists public.campaign_volunteers (
  id         bigint generated by default as identity primary key,
  name       text not null,
  city       text,
  contact    text not null,
  note       text,
  created_at timestamptz not null default now()
);

-- Ayni iletisim bilgisiyle tekrar kayit olusmasin (mukerrer/spam onleme)
create unique index if not exists campaign_volunteers_contact_uniq
  on public.campaign_volunteers (lower(contact));

-- RLS acik + hic policy yok => PostgREST uzerinden kimse okuyamaz/yazamaz.
-- Yazma yalnizca asagidaki security definer fonksiyon uzerinden yapilir.
alter table public.campaign_volunteers enable row level security;
revoke all on public.campaign_volunteers from anon, authenticated;

-- ---------------------------------------------------------------------
-- Kayit ekleme
--   Donus: 'created' | 'duplicate'
--   Ham veriyi asla geri dondurmez.
-- ---------------------------------------------------------------------
create or replace function public.add_volunteer(
  p_name    text,
  p_city    text,
  p_contact text,
  p_note    text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name    text := btrim(coalesce(p_name, ''));
  v_city    text := nullif(btrim(coalesce(p_city, '')), '');
  v_contact text := btrim(coalesce(p_contact, ''));
  v_note    text := nullif(btrim(coalesce(p_note, '')), '');
  v_id      bigint;
begin
  if length(v_name) < 2 or length(v_name) > 120 then
    raise exception 'invalid_name';
  end if;

  if length(v_contact) < 5 or length(v_contact) > 160 then
    raise exception 'invalid_contact';
  end if;

  if v_city is not null and length(v_city) > 60 then
    raise exception 'invalid_city';
  end if;

  if v_note is not null and length(v_note) > 1000 then
    v_note := left(v_note, 1000);
  end if;

  insert into public.campaign_volunteers (name, city, contact, note)
  values (v_name, v_city, v_contact, v_note)
  on conflict (lower(contact)) do nothing
  returning id into v_id;

  if v_id is null then
    return 'duplicate';
  end if;

  return 'created';
end;
$$;

revoke all on function public.add_volunteer(text, text, text, text) from public;
grant execute on function public.add_volunteer(text, text, text, text) to anon, authenticated;

-- ---------------------------------------------------------------------
-- Toplam gonullu sayisi (rozette gosterilir)
--   Yalnizca sayi doner; hicbir kisisel veri disariya cikmaz.
-- ---------------------------------------------------------------------
create or replace function public.volunteer_count()
returns integer
language sql
security definer
set search_path = public
stable
as $$
  select count(*)::integer from public.campaign_volunteers;
$$;

revoke all on function public.volunteer_count() from public;
grant execute on function public.volunteer_count() to anon, authenticated;

-- ---------------------------------------------------------------------
-- Supabase, public semadaki yeni tablolara otomatik yetki verebiliyor.
-- Bu yuzden revoke'u tablo olusturulduktan SONRA tekrarliyoruz.
-- ---------------------------------------------------------------------
revoke all on public.campaign_volunteers from anon, authenticated;

-- ---------------------------------------------------------------------
-- Dogrulama
-- ---------------------------------------------------------------------
select has_table_privilege('anon', 'public.campaign_volunteers', 'SELECT') as anon_okuyabilir,
       public.volunteer_count()                                            as mevcut_kayit;
-- Beklenen: false, 0

-- =====================================================================
-- Yonetici disa aktarimi
--   Kisisel veriyi dondurur -> yalnizca admin PIN'i dogrulandiginda calisir.
--   PIN sunucuda bcrypt ile dogrulanir; verify_access_pin'in hiz siniri
--   burada da gecerlidir (basarisiz denemeler pin_attempts'e yazilir).
-- =====================================================================
create or replace function public.export_volunteers(p_pin text)
returns table (
  id         bigint,
  name       text,
  city       text,
  contact    text,
  note       text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_access_pin('admin', p_pin) then
    raise exception 'unauthorized';
  end if;

  return query
  select v.id, v.name, v.city, v.contact, v.note, v.created_at
  from public.campaign_volunteers v
  order by v.created_at desc;
end;
$$;

revoke all on function public.export_volunteers(text) from public;
grant execute on function public.export_volunteers(text) to anon, authenticated;
