-- Supabase SQL Editor'de, production ortamında bir kez çalıştırın.
-- Günlük yedekleme ayrıca Supabase Dashboard > Database > Backups altında açılmalıdır.

create table if not exists public.campaign_citizens (
  id bigint generated by default as identity primary key,
  citizen_hash text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.campaign_submissions (
  id bigint generated by default as identity primary key,
  citizen_hash text not null references public.campaign_citizens(citizen_hash) on delete cascade,
  recipient_type text not null check (recipient_type in ('cb', 'mb', 'mp')),
  recipient_id integer,
  petition_number text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.campaign_submission_audit (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.campaign_submissions(id) on delete cascade,
  action text not null check (action in ('created', 'confirmed')),
  created_at timestamptz not null default now()
);

alter table public.campaign_citizens enable row level security;
alter table public.campaign_submissions enable row level security;
alter table public.campaign_submission_audit enable row level security;

revoke all on public.campaign_citizens from anon, authenticated;
revoke all on public.campaign_submissions from anon, authenticated;
revoke all on public.campaign_submission_audit from anon, authenticated;

-- İstemci tabloya doğrudan yazmaz; aşağıdaki security definer fonksiyonunu çağırır.

drop policy if exists "public citizen insert" on public.campaign_citizens;
create policy "public citizen insert"
on public.campaign_citizens for insert to anon, authenticated
with check (length(citizen_hash) = 64 and citizen_hash ~ '^[0-9a-f]{64}$');

drop policy if exists "public submission insert" on public.campaign_submissions;
create policy "public submission insert"
on public.campaign_submissions for insert to anon, authenticated
with check (
  length(petition_number) between 20 and 80
  and petition_number ~ '^7527-(CB|MB|MP)-[0-9]{8}-[0-9A-F]+$'
  and recipient_type in ('cb', 'mb', 'mp')
);

create or replace function public.record_campaign_submission(
  p_citizen_hash text,
  p_recipient_type text,
  p_recipient_id integer,
  p_petition_number text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  submission_id bigint;
begin
  if p_citizen_hash !~ '^[0-9a-f]{64}$'
     or p_recipient_type not in ('cb', 'mb', 'mp')
     or p_petition_number !~ '^7527-(CB|MB|MP)-[0-9]{8}-[0-9A-F]+$' then
    raise exception 'invalid_submission';
  end if;

  insert into public.campaign_citizens (citizen_hash)
  values (p_citizen_hash)
  on conflict (citizen_hash) do nothing;

  insert into public.campaign_submissions
    (citizen_hash, recipient_type, recipient_id, petition_number)
  values
    (p_citizen_hash, p_recipient_type, p_recipient_id, p_petition_number)
  on conflict (petition_number) do nothing
  returning id into submission_id;

  if submission_id is not null then
    insert into public.campaign_submission_audit (submission_id, action)
    values (submission_id, 'created');
  end if;

  return submission_id;
end;
$$;

revoke all on function public.record_campaign_submission(text, text, integer, text) from public;
grant execute on function public.record_campaign_submission(text, text, integer, text) to anon, authenticated;

-- Günlük yedek için: Supabase Dashboard > Database > Backups bölümünde
-- günlük backup/PITR politikasını etkinleştirin ve geri yükleme tatbikatı yapın.