-- =====================================================================
-- 7527iptal.org - Erisim PIN yonetimi
-- Supabase Dashboard > SQL Editor'de BIR KEZ calistirin.
-- PIN yer tutucularini (<<GATE_PIN>>, <<ADMIN_PIN>>) 6 haneli gercek degerlerle degistirip calistirin.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- 1) PIN tablosu -------------------------------------------------------
create table if not exists public.app_access_pins (
  scope       text primary key check (scope in ('gate', 'admin')),
  pin_hash    text not null,
  updated_at  timestamptz not null default now()
);

-- RLS acik + hic policy yok + revoke all
--  => PostgREST uzerinden anon/authenticated bu tabloyu OKUYAMAZ.
--     Sadece asagidaki security definer fonksiyon erisebilir.
alter table public.app_access_pins enable row level security;
revoke all on public.app_access_pins from anon, authenticated;

-- 2) Deneme kaydi (brute-force sinirlama) ------------------------------
create table if not exists public.pin_attempts (
  id           bigint generated by default as identity primary key,
  scope        text not null,
  ok           boolean not null,
  attempted_at timestamptz not null default now()
);
create index if not exists pin_attempts_scope_time_idx
  on public.pin_attempts (scope, attempted_at desc);

alter table public.pin_attempts enable row level security;
revoke all on public.pin_attempts from anon, authenticated;

-- 3) Dogrulama fonksiyonu ----------------------------------------------
create or replace function public.verify_access_pin(p_scope text, p_pin text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  stored   text;
  failures integer;
  result   boolean;
begin
  if p_scope not in ('gate', 'admin') then
    raise exception 'invalid_scope';
  end if;

  -- Bicim disi girdiyi hic hash'leme, kaydetme
  if p_pin is null or p_pin !~ '^[0-9]{6}$' then
    return false;
  end if;

  -- Son 15 dakikadaki basarisiz deneme sayisi
  select count(*) into failures
  from public.pin_attempts
  where scope = p_scope
    and not ok
    and attempted_at > now() - interval '15 minutes';

  if failures >= 20 then
    raise exception 'too_many_attempts';
  end if;

  select pin_hash into stored
  from public.app_access_pins
  where scope = p_scope;

  if stored is null then
    return false;
  end if;

  result := (extensions.crypt(p_pin, stored) = stored);

  insert into public.pin_attempts (scope, ok) values (p_scope, result);

  -- Dogru PIN girilince o scope'un sayaci sifirlanir
  if result then
    delete from public.pin_attempts
    where scope = p_scope and not ok;
  end if;

  return result;
end;
$$;

revoke all on function public.verify_access_pin(text, text) from public;
grant execute on function public.verify_access_pin(text, text) to anon, authenticated;

-- 4) PIN'leri yaz -------------------------------------------------------
-- bcrypt (cost 12). Acik PIN veritabaninda HICBIR YERDE saklanmaz.
insert into public.app_access_pins (scope, pin_hash, updated_at) values
  ('gate',  extensions.crypt('<<GATE_PIN>>', extensions.gen_salt('bf', 12)), now()),
  ('admin', extensions.crypt('<<ADMIN_PIN>>', extensions.gen_salt('bf', 12)), now())
on conflict (scope) do update
  set pin_hash = excluded.pin_hash,
      updated_at = now();

-- 5) Dogrulama ----------------------------------------------------------
select 'gate  dogru PIN  ' as test, public.verify_access_pin('gate',  '<<GATE_PIN>>') as sonuc
union all select 'gate  yanlis PIN ', public.verify_access_pin('gate',  '000000')
union all select 'admin dogru PIN  ', public.verify_access_pin('admin', '<<ADMIN_PIN>>')
union all select 'admin yanlis PIN ', public.verify_access_pin('admin', '999999');
-- Beklenen: true, false, true, false
